.github/CODEOWNERS, cspell.json
Adds a CODEOWNERS file in order to assign reviewers faster. We will add frontenders from Localyze as codeowerns by now.
=> [TREX-7] chore: add codeowners file

.github/workflows/on_release_publish.yml, packages/components/package.json, packages/eslint-config/package.json, packages/theme/package.json, packages/tsconfig/package.json
In order to avoid trying to publish packages in every merging to main, we added a path to `packages` in the Release Github Action. Thanks, @richbachman 🙏🏻 
Plus: We updated some package versions before publishing them to npm.
=> fix: Add path packages to Release action

.changeset/wise-spies-leave.md, cspell.json, packages/components/src/index.ts, packages/components/src/primitives/Box/BaseBox.tsx, packages/components/src/primitives/Text/BaseText.tsx, packages/components/src/primitives/Text/Text.stories.tsx, packages/components/src/primitives/Text/Text.test.tsx, packages/components/src/primitives/Text/Text.tsx, packages/components/src/primitives/Text/index.ts
This is the first version of the Text primitive component. Text is a slimmed down version of Box that should be used to create all text styles in Pluto.
Text comes with all text related variant props, i.e: color, fontSize and lineHeight. Text also includes display variants, and cursor variants.
The variants are also responsive as they are in Box.
=> feat(components): add text primitive component

.github/workflows/visual_regression_tests.yml
To avoid running visual regression tests with Chromatic for every new dependabot PRs, we will remove these branches from the vrt action.
=> chore: remove dependabot branchs from visual regression tests action

.github/workflows/visual_regression_tests.yml
This PR tries to fix the dependabot pattern we added in the visual regression tests action to remove the necessity of running this action for some branches.
=> fix: dependabot pattern on vrt action

.changeset/pink-cups-sniff.md, .changeset/plenty-guests-drop.md, packages/components/package.json, packages/theme/package.json, packages/theme/src/index.ts
This PR adds the correct types to the theme package and updates the peerDependencies for both theme and components. This should fix the type autocomplete issue in the talent-web app.
=> fix(theme): added types to export and correct peerDeps

.changeset/happy-crews-protect.md, .changeset/warm-pigs-arrive.md, packages/components/src/components/Heading/Heading.stories.tsx, packages/components/src/components/Heading/Heading.test.tsx, packages/components/src/components/Heading/Heading.tsx, packages/components/src/components/Heading/index.ts, packages/components/src/index.ts, packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap, packages/theme/src/theme/default.ts
This adds the Heading component. It can be multiple sizes, and render as any valid heading element. Heading also includes a default bottom margin, which can be overridden to have no bottom margin.
This also updates the theme package with new fontSizes and lineHeights.
=> feat(components): add heading component

.changeset/lucky-cows-lay.md, .changeset/shy-games-end.md, cspell.json, packages/components/src/components/Button/Button.stories.tsx, packages/components/src/components/Button/Button.test.tsx, packages/components/src/components/Button/Button.tsx, packages/components/src/components/Button/index.ts, packages/components/src/index.ts, packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap, packages/theme/src/theme/default.ts
This adds the button component. It only has one variant right now and two sizes. Stories and tests are added as well. Along with this, I added a `loading` state to our theme, so we can style `aria-busy` elements.
=> feat(components): add button component

.changeset/late-mirrors-agree.md, .changeset/wicked-needles-hang.md, packages/components/src/components/Button/Button.stories.tsx, packages/components/src/components/Button/Button.test.tsx, packages/components/src/components/Button/Button.tsx, packages/components/src/index.ts
Adds leading and trailing icons to Primary Button.
=> feat: add icon to primary button

.changeset/grumpy-actors-judge.md, packages/theme/package.json
Updates the react peer dependencies on pluto theme package in order to fix an issue on repos that are using react 18.
=> fix: update theme peer dependecies version

.changeset/cool-eagles-smoke.md, packages/components/src/components/Table/THead.tsx, packages/components/src/components/Table/Table.stories.tsx, packages/components/src/components/Table/Th.tsx
Adding a `stickyHeader` and `top` prop to the Table Header so they can be sticky to the top of a container or page.
=> feat(components): add sticky header and top props to table header

.changeset/fair-bobcats-repeat.md, packages/components/src/components/Heading/Heading.stories.tsx, packages/components/src/components/Heading/Heading.tsx
This PR allows breakpoints in `Heading`'s size prop.
https://user-images.githubusercontent.com/1165437/198074550-f249b7e5-756e-49ef-bcfa-5da023419e81.mp4
=> feat(components): allow breakpoints in heading size

.changeset/large-baboons-dress.md, packages/components/src/components/Input/Input.stories.tsx, packages/components/src/components/Input/Input.tsx, packages/components/src/components/InputBox/InputBox.tsx
Adds the leading icon and trailing icon props to input.
=> feat(components): add input leading and trailing icons

.changeset/mighty-melons-breathe.md, packages/components/src/components/Search/Search.stories.tsx, packages/components/src/components/Search/Search.test.tsx, packages/components/src/components/Search/Search.tsx, packages/components/src/components/Search/index.ts, packages/components/src/index.ts
This adds the Search component, which is an Input with the type set to `search.
=> feat(components): add search input component

.changeset/big-scissors-live.md, packages/components/src/components/Button/Button.stories.tsx, packages/components/src/components/Button/Button.tsx
- Add `fullWidth` prop to buttons
=> feat(components): add full width prop to button

.changeset/eleven-ads-check.md, .changeset/strange-beans-juggle.md, .changeset/tall-eagles-beg.md, packages/components/src/components/Avatar/Avatar.stories.tsx, packages/components/src/components/Avatar/Avatar.tsx, packages/components/src/components/Avatar/getAvatarColor.test.ts, packages/components/src/components/Avatar/getAvatarColor.ts, packages/components/src/components/Avatar/index.ts, packages/components/src/components/RichText/RichText.tsx, packages/design-tokens/src/tokens/color.tokens.json, packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap, packages/theme/src/theme/default.ts
Added a `getAvatarColor` function to randomly generate an Avatar background color. This function isn't used by default, but exported so it can be used in other applications.
Also added the new avatar background color tokens to the theme and design tokens packages.
=> feat(components): add getAvatarColor function to Avatar

.changeset/witty-poets-destroy.md, packages/components/src/components/InputBox/InputBox.tsx
Updates the InputBox background and border color based on design feedback.
- Background: `colorBackgroundWeakest` changed to `colorBackground`
- Background hover: `colorBackgroundWeak` changed to `colorBackgroundWeakest`
- Border: `colorBorder` changed to `colorBorderWeakest`
=> fix(components): changed background and border input box colors

.changeset/funny-toes-melt.md, .changeset/silly-terms-drum.md, package.json, packages/components/package.json, packages/components/src/components/Button/Button.tsx, packages/components/src/components/Modal/Modal.stories.tsx, packages/components/src/components/Modal/Modal.test.tsx, packages/components/src/components/Modal/Modal.tsx, packages/components/src/components/Modal/ModalBody.tsx, packages/components/src/components/Modal/ModalFooter.tsx, packages/components/src/components/Modal/ModalHeader.tsx, packages/components/src/components/Modal/ModalHeading.tsx, packages/components/src/components/Modal/ModalSubHeading.tsx, packages/components/src/components/Modal/index.ts, packages/components/src/index.ts, packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap, packages/theme/src/styles/base.tsx, packages/theme/src/theme/default.ts, yarn.lock
This PR adds the initial release of the modal component. The component uses the [AriaKit](https://ariakit.org/components/dialog) primitive to handle the modal functionality. Currently I'm leaving the modal API pretty open, as in straight exports from AriaKit. This is mainly to get a feel for how this modal will work with the current application. We will be adding a more dev friendly modal in the future where the api will be more refined. I have also not included any animations in this first version. Because of the way the primitive is built, we'll need to setup an animation library like Framer first in Pluto. I'd like to spend more time researching Framer or another option first before adding animations in this PR.
This also includes an update to the theme to include the backdrop styles.
=> feat(components): added Modal component

.changeset/tall-clouds-happen.md, packages/components/src/components/Avatar/Avatar.stories.tsx, packages/components/src/components/Avatar/Avatar.tsx
Adds the **extra-large** size to Avatar component.
=> feat(components): add extra-large size to Avatar

.changeset/cool-seas-end.md, packages/components/src/components/FileUploader/FileUploaderButton.test.tsx, packages/components/src/components/FileUploader/FileUploaderButton.tsx
The upload button was replacing the onClick with its own implementation. So, if we added an `onClick` prop, which is allowed, it would never be called.
- See the tests
=> fix: [FileUploaderButton] call onClick prop

.changeset/spicy-zebras-dream.md, packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap, packages/theme/src/theme/default.ts
Adds the new decorative01 and decorative02  background colors to the default theme.
=> feat(tokens): add new background colors to the default theme

.changeset/sharp-bears-rescue.md, packages/components/src/components/Button/Button.stories.tsx, packages/components/src/components/Button/Button.tsx
Adds new button variant called `outline` and it has transparent background.
=> fix(components): add new Button variant

.changeset/poor-hornets-cheer.md, packages/components/src/components/Button/Button.tsx
Allow buttons to receive `target` and `rel` as prop to use with `as="a"`.
=> fix(components): add rel and target as props on the button

.changeset/late-eels-protect.md, packages/components/src/components/Modal/Modal.stories.tsx, packages/components/src/components/Tooltip/Tooltip.stories.tsx, packages/components/src/components/Tooltip/Tooltip.test.tsx, packages/components/src/components/Tooltip/Tooltip.tsx, packages/components/src/components/Tooltip/index.ts, packages/components/src/index.ts
This PR adds the initial release of the tooltip component. The component uses the [AriaKit](https://ariakit.org/components/tooltip) primitive to handle the functionality. Currently I'm leaving the tooltip API pretty open, as in straight exports from AriaKit. This is mainly to get a feel for how this tooltip will work with the current application. We will be adding a more dev friendly tooltip in the future where the api will be more refined. I have also not included any animations in this first version. Because of the way the primitive is built, we'll need to setup an animation library like Framer first in Pluto. I'd like to spend more time researching Framer or another option first before adding animations in this PR.
=> feat(components): add Tooltip component

.changeset/dull-apples-relate.md, cspell.json, packages/components/src/components/Modal/Modal.stories.tsx, packages/components/src/components/Modal/Modal.tsx, packages/components/src/components/Tooltip/Tooltip.tsx
Fixes the `noonce` typescript error we're seeing when using Modal and Tooltip in the client application.
=> fix(components): omit noonce from ariakit props

.changeset/sharp-brooms-run.md, packages/components/src/components/Modal/Modal.stories.tsx, packages/components/src/components/Modal/ModalBody.tsx
Added the `disableOverflow` prop to ModalBody, so a dropdown can be used inside the modal body area. This is a temporary solution for a product flow that has a multistep modal with a single dropdown as the first step. There is a plan/epic to replace this flow with a different one.
=> chore(components): add disableOverflow prop to ModalBody

.changeset/fluffy-monkeys-jog.md, packages/components/src/components/Dropzone/Dropzone.stories.tsx, packages/components/src/components/Dropzone/Dropzone.test.tsx, packages/components/src/components/Dropzone/Dropzone.tsx, packages/components/src/components/Dropzone/getFileRestrictionText.test.ts, packages/components/src/components/Dropzone/getFileRestrictionText.ts
Use `fileTypes` and `maxFileSize` props to generate the file size and type restriction text and according error messages.
Before this change passing one of the 2 properties had no influence on what was displayed as file size or type restrictions.
Now the dropzone can also be used to upload any file or files of a specific type.
---
---
=> fix(components): dynamic file restriction texts for Dropzone

.changeset/real-mirrors-lay.md, .changeset/warm-comics-wonder.md, .storybook/preview.js, packages/components/src/components/Anchor/Anchor.stories.tsx, packages/components/src/components/Avatar/Avatar.tsx, packages/components/src/components/Callout/Callout.stories.tsx, packages/components/src/components/FileUploader/FileUploader.tsx, packages/components/src/components/Heading/Heading.tsx, packages/components/src/components/InputBox/InputBox.tsx, packages/components/src/components/Label/Label.tsx, packages/components/src/components/List/OrderedList.tsx, packages/components/src/components/List/UnorderedList.tsx, packages/components/src/components/Paragraph/Paragraph.tsx, packages/theme/src/styles/base.tsx
This is mainly a change to the theme package. After some research I slimmed down the BaseStyles so they can be used in the client app.
This change also corrects the components so they no longer rely on the Preflight so that doesn't need to be used in the client app. You can see a list of changes [here](https://github.com/Localitos/pluto/pull/268/files#diff-44f1f0f54858c7c07832fd685be11e915705c45a4a241e9ae452d92563432139).
=> fix(theme): adjust base styles for app usage

.changeset/dry-dolphins-jump.md, .changeset/popular-terms-tease.md, .changeset/silent-bugs-dress.md, .github/workflows/on_pull_request.yml, babel.config.json, jest.config.js, package.json, packages/components/src/components/Button/Button.tsx, packages/components/src/components/Dropzone/Dropzone.tsx, packages/components/src/components/FileUploader/FileUploader.tsx, packages/components/src/components/Icon/Icon.stories.tsx, packages/components/src/components/InputBox/InputBox.tsx, packages/components/src/components/Modal/ModalFooter.tsx, packages/components/src/components/Modal/ModalHeader.tsx, packages/components/src/primitives/Box/Box.stories.tsx, packages/design-tokens/config.json, packages/design-tokens/src/tokens/border-style.tokens.json, packages/design-tokens/src/tokens/color.tokens.json, packages/theme/package.json, packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap, packages/theme/src/theme/default.ts, yarn.lock
This sets up the use of the Design Tokens package within the Theme package. So now the theme is built using the design tokens. So now if we change a token or add a new one, it will be added to the theme package automatically.
In doing so, there is a change to the border style theme values:
- `borderDashed` changed to `borderStyleDashed`
- `borderSolid` changed to `borderStyleSolid`
=> feat(design-tokens): add separate js build files

.changeset/cuddly-months-fix.md, packages/components/src/components/Dropzone/Dropzone.tsx
The default message was not changing when the a new file was being dragged so we want to reset the errors when the isDragActive is true and the isDragReject is false
=> fix(components): add isDragActive to reset errors on Dropzone

.changeset/dry-bobcats-doubt.md, packages/components/src/components/Heading/Heading.stories.tsx
Adding mobile viewports to the Heading breakpoint story. These show up in Chromatic snapshots.
=> chore(components): add heading mobile chromatic story

.changeset/yellow-zoos-run.md, packages/components/src/components/Dropzone/Dropzone.stories.tsx, packages/components/src/components/Dropzone/Dropzone.test.tsx, packages/components/src/components/Dropzone/Dropzone.tsx, packages/components/src/components/Dropzone/getFileRestrictionText.test.ts, packages/components/src/components/Dropzone/getFileRestrictionText.ts
We removed the isDragReject conditional for error handling. Now the dropzone will only display errors after drop. We also added a maxFiles prop.
=> fix(components): refactor dropzone to remove isDragReject

.changeset/chatty-stingrays-deliver.md, packages/components/src/components/Dropzone/getFileRestrictionText.test.ts, packages/components/src/components/Dropzone/getFileRestrictionText.ts
The dropzone was not including the option for a limit under 1mb so we changed the method to include kb.
=> fix(components): adjusted file size limit in dropzone to include kb

.changeset/dull-horses-return.md, packages/components/src/components/ProgressBar/ProgressBar.stories.tsx, packages/components/src/components/ProgressBar/ProgressBar.test.tsx, packages/components/src/components/ProgressBar/ProgressBar.tsx
Adds `backgroundColor`, `indicatorColor`, height (`h`) and `borderRadius` props to the Progress bar so we can better customize this component when we're using it.
1. Run the Storybook application with `yarn start`
2. Navigate to the Progress Bar tab
=> feat(components): add height, color and radius to progress bar

.changeset/healthy-guests-marry.md, packages/components/src/components/ProgressBar/ProgressBar.stories.tsx, packages/components/src/components/ProgressBar/ProgressBar.test.tsx, packages/components/src/components/ProgressBar/ProgressBar.tsx
By replacing the height of the progress bar with a small/large size variant we simplify the usage of the component and prevent issues at later stages since the developers no longer have to worry about using the right height.
=> fix(components): replace progress bar height with size variant

.changeset/fluffy-fans-kick.md, .changeset/thick-mangos-smash.md, packages/design-tokens/config.json, packages/design-tokens/package.json, packages/design-tokens/src/index.ts, packages/theme/src/theme/default.ts
This should fix the downstream teams import errors by not importing a non-compiled js file from the design token package.
- Exports the tokens in on main index file for design-tokens
- Imports the tokens from the main file in the theme
=> fix(design-tokens): export js tokens as one index file

.changeset/yellow-lies-heal.md, packages/components/src/components/Modal/Modal.tsx
In Talent-web, the modal was below the other elements in the page for some reason. This is adding the zIndex prop so that we can adjust for the zIndex in the modal.
I tried to add a story but I couldn't figure out a good way to test this.
=> feat: [no-issue] add zIndex prop to modal

.changeset/strange-cycles-dream.md, packages/components/src/components/Modal/Modal.tsx
We didn't actually end up needing this optional zIndex prop so I am removing it here.
=> feat: remove zIndex from modal

.github/dependabot.yml, .kodiak.toml
Attempting to fix the Kodiak auto-merge config, by using the default settings except for dependabot. This also should auto-approve dependabot patches and minors.
=> chore: correct kodiak version

.changeset/curly-kids-love.md, packages/components/src/components/Select/Select.stories.tsx, packages/components/src/components/Select/Select.test.tsx, packages/components/src/components/Select/Select.tsx, packages/components/src/components/Select/SelectItem.tsx
Adds a label prop to SelectItem. This allows select options to have different labels and values, i.e.:
```
{ value: 'USA', text: "United States" }
```
=> fix(components): add missing label to select items

.changeset/tricky-dots-hide.md, packages/components/src/components/Select/Select.stories.tsx, packages/components/src/components/Select/Select.test.tsx, packages/components/src/components/Select/Select.tsx, packages/components/src/components/Select/SelectItem.tsx
Adjusted the base functionality so it works as a multiselect. In order to get a multiselect, an array should be passed to either `defaultValue` or `value`.
- Also removed the need for the `initial` prop on `SelectItem` by adding default text if a Select value is an empty string.!
=> feat(components): added multiselect ability to select

.changeset/poor-buttons-joke.md, packages/components/src/components/Toast/Toast.stories.tsx, packages/components/src/components/Toast/Toast.test.tsx, packages/components/src/components/Toast/Toast.tsx, packages/components/src/components/Toast/ToastContainer.tsx, packages/components/src/components/Toast/ToastContext.tsx, packages/components/src/components/Toast/ToastViewport.tsx, packages/components/src/components/Toast/index.ts, packages/components/src/components/Toast/types.ts, packages/components/src/components/Toast/useToast.tsx
Added a `useToast` hook and `ToastContainer` component that can be added to downstream applications and will make firing toasts a simpler process, and will require much less code duplication. 
Thanks @nyan07 for the inspiration!
=> feat(components): added useToast hook and ToastContainer

.changeset/lemon-zoos-draw.md, packages/design-tokens/src/tokens/border-radius.tokens.json, packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
```
borderRadius={{ _: "borderRadius0", md: "borderRadius30" }}
```
This is necessary to avoid adding a borderRadius to an element in the app we are working on now. 
---- 
Plus: It also adds the `borderRadius35` because it's needed in the talent app.
=> feat: add new borderRadius tokens

.changeset/nasty-experts-divide.md, .changeset/weak-bears-wonder.md, packages/components/package.json, packages/components/src/components/Tabs/Tab.tsx, packages/components/src/components/Tabs/TabList.tsx, packages/components/src/components/Tabs/TabPanel.tsx, packages/components/src/components/Tabs/TabPanels.tsx, packages/components/src/components/Tabs/Tabs.stories.tsx, packages/components/src/components/Tabs/Tabs.test.tsx, packages/components/src/components/Tabs/Tabs.tsx, packages/components/src/components/Tabs/TabsContext.tsx, packages/components/src/components/Tabs/index.ts, packages/components/src/components/Tabs/types.ts, packages/components/src/index.ts, packages/components/src/primitives/Box/Box.tsx, packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap, packages/theme/src/theme/default.ts
Added Tabs component, stories and tests.
Also updated the theme border styles and color objects, so the values were no longer needed in Box.
- Added `none` to border styles theme object.
- Added `transparent` to colors theme object.
=> feat(components): add tabs component and stories

.changeset/red-pans-rescue.md, packages/components/src/components/Table/Table.stories.tsx
The sticky headers story for table needed a wrapper to be seen on the story docs.
https://user-images.githubusercontent.com/52461415/214010593-d4625b1e-442b-4280-aedd-2c35d7043a14.mov
=> fix(components): added sticky headers wrapper to table

.changeset/real-mice-remain.md, packages/components/src/components/FormInput/FormInput.tsx, packages/components/src/components/FormSelect/FormSelect.stories.tsx, packages/components/src/components/FormSelect/FormSelect.tsx, packages/components/src/components/FormTextArea/FormTextArea.tsx
- [FormInput, FormSelect, FormTextArea] - Removed absolute positioning in form element HelpText.
- [FormSelect] - Added a controlled story example.
=> fix(components): removed absolute positioning of helptext

.changeset/long-lobsters-study.md, packages/components/src/components/List/ListItem.tsx
Fixed the missing bottom margins in ListItem. The last ListItem does not include the bottom margin.
=> fix(components): added spacing to list items

.changeset/healthy-walls-sparkle.md, packages/components/src/components/FormTextArea/ControlledFormTextArea.tsx, packages/components/src/components/FormTextArea/FormTextArea.stories.tsx, packages/components/src/components/FormTextArea/FormTextArea.test.tsx, packages/components/src/components/FormTextArea/FormTextArea.tsx, packages/components/src/components/FormTextArea/index.ts
Added ContolledFormTextArea so TextArea can be easily used with React Hook Form.
=> feat(components): add ControlledFormTextArea for react hook form

.changeset/pink-falcons-work.md, packages/components/src/components/FormSelect/ControlledFormSelect.tsx, packages/components/src/components/FormSelect/FormSelect.stories.tsx, packages/components/src/components/FormSelect/FormSelect.test.tsx, packages/components/src/components/FormSelect/FormSelect.tsx, packages/components/src/components/FormSelect/index.ts
Added a ControlledFormSelect version so it can be easier used with React Hook Form.
=> feat(components): add ControlledFormSelect for react hook form

.changeset/slimy-phones-pay.md, packages/components/src/components/Heading/Heading.stories.tsx, packages/components/src/components/Heading/Heading.tsx
Adds the `colorTextInverse` to "HeadingFontColors" type.
=> feat: add textInverse color to Heading component

.changeset/five-radios-knock.md, packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap, packages/theme/src/theme/default.ts
Add the option to set the boxShadow as "none". This is very useful for elements that may have a box shadow value in a certain screen breakpoint but not on others (ex.: mobile vs desktop).
Example usage
```javascript
boxShadow={{ _: "shadow", md: "none" }}
```
=> feat(theme): add none value to box shadow

.changeset/thirty-donuts-begin.md, packages/design-tokens/src/tokens/color.tokens.json, packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
- Fix color token since the changed value is actually colorAvatarBackgroundLightBlue
before:
after:
the correct color can be checked on storybook /docs/components-avatar--docs
=> [NOISSUE] fix: add right value to colorAvatarBackgroundPink token

.changeset/sixty-nails-warn.md, packages/components/src/components/ProgressBar/ProgressBar.test.tsx, packages/components/src/components/ProgressBar/ProgressBar.tsx
- Change the ProgressBar component to use Box.div instead of Styled components so the token overwriting can be correct
- you can edit `.storybook/preview.js` rewriting tokens like below. This was not affecting the component before and now it works properly
```typescript
<ThemeProvider
theme={{
...theme,
colors: {
...theme.colors,
colorAvatarBackgroundGreen: "limegreen",
colorAvatarBackgroundPink: "purple",
},
}}
>
```
and change stories snippet like
```typescript
export const WithCustomColors = (): JSX.Element => (
<Box.div display="flex" flexDirection="column" gap="space40">
<ProgressBar
backgroundColor="colorAvatarBackgroundPink"
indicatorColor="colorAvatarBackgroundGreen"
value={25}
/>
<Box.div backgroundColor={"colorAvatarBackgroundGreen"}>Hello!</Box.div>
<Box.div …
```
=> fix: use Box.div on ProgressBar fixing tokens usage

.changeset/metal-phones-impress.md, packages/design-tokens/src/tokens/color.tokens.json, packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
- change colorIconMap from #4A63FC to #0B1F9C
=> fix(tokens): Replace map icon token

.changeset/green-sloths-wait.md, packages/components/src/components/FileUploader/FileUploader.stories.tsx, packages/components/src/components/FileUploader/FileUploader.tsx, packages/components/src/components/FileUploader/FileUploaderTitle.tsx
We should also handle the file uploaded title when the component status is disabled. For this case, we are sending the status to the FileUploaderTitle and checking if the status is disabled to create the link or not in the title.
=> fix: make file upload title disabled

.changeset/slimy-crabs-attend.md, packages/components/src/components/Checkbox/Checkbox.stories.tsx, packages/components/src/components/Checkbox/ControlledCheckbox/ControlledCheckbox.test.tsx, packages/components/src/components/Checkbox/ControlledCheckbox/ControlledCheckbox.tsx
This creates a ControlledCheckbox component to be easily used with React Hook Forms.
=> feat: create controlled checkbox

.github/dependabot.yml
This PR:
* use the `rebase-strategy` as disabled to stop rebasing dependabot PRs and making us rebase them when merging it
=> chore: disable auto rebase from dependabot

.changeset/spicy-seals-deny.md, packages/components/src/components/FormSelect/ControlledFormSelect.tsx, packages/components/src/components/Select/Select.tsx
The onBlur of the Select was getting triggered when clicking on a menu item causing issues with validating on blur. The Select now follows a similar approach seen in AriaKit's FormSelect component to prevent this.
I've also made `control` prop required for the `ControlledFormSelect` component as the component throws an error without it.
=> Select component fixes

.changeset/funny-ears-cheer.md, packages/components/src/components/Button/Button.tsx
The Button as Link's color and text decoration was getting overwritten on hover by other conflicting design systems. This makes those styles explicit so that this doesn't happen.
Issue:
=> Fix button stylings getting overwritten

.changeset/serious-avocados-invent.md, packages/components/src/components/FileUploader/FileUploader.tsx
In case of error the component was showing the trash icon instead of the upload button.
- Bug fix (non-breaking change that fixes an issue)
=> fix: show upload button in case of error

.changeset/serious-avocados-invent.md, packages/components/src/components/FileUploader/FileUploader.tsx
Reverts Localitos/pluto#763
* The changes were made to validation errors. But we realized that the current behavior is only specific for uploading errors. So, we need to discuss before with the Designers if we want the same view for both cases.
=> Revert "fix: show upload button in case of error"

.changeset/heavy-bottles-eat.md, packages/components/src/components/Radio/ControlledRadioGroup/ControlledRadioGroup.test.tsx, packages/components/src/components/Radio/ControlledRadioGroup/ControlledRadioGroup.tsx, packages/components/src/components/Radio/Radio.stories.tsx, packages/components/src/components/Radio/Radio.tsx, packages/components/src/components/Radio/index.ts
- Add a controlled Radio Group
- Enforces Radio component to have margin bottom zero
RadioGroup can be used with React Hook Form by passing a `control` variable not needing to handle values outside of it
=> feat(components): add controlled RadioGroup, enforce Radio margin

.changeset/four-shrimps-run.md, packages/components/src/components/Radio/ControlledRadioGroup/ControlledRadioGroup.tsx
- Since ControlledRadioGroup is not using the passed ref I'm removing it
=> fix(components): remove unnecessary forwardRef from ControlledRadioGroup

.changeset/nine-socks-matter.md, packages/components/src/components/Tabs/Tab.tsx, packages/components/src/components/Tabs/TabList.tsx
- z-index negative does not work well in pages that has a background (not transparent) and the divider was hidden in some places
=> fix: change tab z-index to not be hidden when there is background

.changeset/modern-experts-attend.md, packages/components/src/components/Callout/Callout.stories.tsx, packages/components/src/components/Callout/Callout.tsx
This allows use of a custom icon with a variant of the callout component.
=> feat: support custom icon with callout component

.changeset/slimy-hotels-explain.md, packages/components/src/components/Table/Table.stories.tsx, packages/components/src/components/Tabs/Tabs.stories.tsx
The way were doing the args in the Table and Tabs components was outdated, so I updated the component docs.
Before:
After:
=> fix(components): fix docs bug in Tabs and Table components

.changeset/rare-poems-join.md, packages/eslint-config/.eslintrc.js
Turns off capitalized comments eslint rule which was more annoying in cases when you're temporarily commenting out code
=> Turn off capitalized comments eslint rule

.changeset/tender-plums-think.md, packages/design-tokens/src/tokens/size.tokens.json
Adds additional icon size tokens to support icon sizes from 2.5rem to 4.5rem.
=> chore(design-tokens): add icons sizes from 80 to 160

.changeset/soft-laws-behave.md, packages/components/src/components/Checkbox/Checkbox.tsx, packages/components/src/components/Radio/Radio.tsx
This PR:
* Removes the red color from Radio and Checkbox components in the error state.
* Changes the label color to "colorTextStrongest"
=> feat: updates radio and checkbox labels styles

.changeset/lovely-gorillas-mix.md, packages/components/src/components/Icon/LucideIcons.ts, packages/components/src/components/Icon/types/LucideIconName.ts
Adds the "copy" Lucid Icon to our available Icons list
=> feat: add lucid copy icon to list

.changeset/late-pillows-eat.md, packages/eslint-config/package.json, yarn.lock
While working on Pluto and running tests, I saw that we have lots of warnings like this:
```
console.error
Warning: An update to Radio inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
at __scopeRadio (/Users/anavale/src/pluto/node_modules/@radix-ui/react-radio-group/dist/packages/react/radio-group/src/Radio.tsx:36:7)
at children (/Users/anavale/src/pluto/node_modules/@radix-ui/react-slot/dist/packages/react/slot/src/Slot.tsx:61:11)
at children …
```
=> chore: update eslint-plugin-jest-dom

.changeset/plenty-turtles-poke.md
- After merging these packages we are bumping Pluto's version
word-wrap from 1.2.3 to 1.2.5 (#942)
eslint-plugin-cypress from 2.12.1 to 2.15.1 (#1017)
react-hook-form from 7.43.2 to 7.47.0 (#1022)
html-react-parser from 3.0.9 to 3.0.16 (#789)
react-router-dom from 6.8.2 to 6.17.0 (#1035)
@adobe/css-tools from 4.0.1 to 4.3.1 (#981)
lint-staged from 13.1.2 to 15.0.2 (#1050)
@uppy/core from 3.0.6 to 3.6.0 (#1054)
@storybook/addon-docs from 7.0.0-rc.4 to 7.5.1 (#1052)
jest-environment-jsdom from 29.4.0 to 29.7.0 (#1000)
@storybook/addon-viewport from 7.0.22 to 7.5.1 (#1051)
tough-cookie from 4.1.2 to 4.1.3 (#919)
turbo from 1.10.3 to 1.10.16 (#1049)
@heroicons/react from 2.0.16 to 2.0.18 (#904)
semver from 5.7.1 to 5.7.2 (#923)
=> chore: bump several dependencies fixing security alerts and packages version

.jest/jest-setup.ts, package.json, yarn.lock
We might want to avoid silent errors on console
Make any test emit an warning like removing a waitFor from `packages/components/src/components/Avatar/useGetImageOrientation.test.ts`
=> chore: add jest-fail-on-console to avoid silent logs that could be errors

.changeset/healthy-lobsters-tie.md, packages/components/src/components/Menu/Menu.stories.tsx, packages/components/src/components/Menu/Menu.test.tsx, packages/components/src/components/Menu/Menu.tsx
We need to be able to disable the buttons in the menu. Therefore I've added the disabled prop to the menu items here.
Tests were added for this
=> feat(components): add disabled props to Menu MenuItems

.changeset/flat-zebras-taste.md, packages/components/src/components/Icon/LucideIcons.ts, packages/components/src/components/Icon/types/LucideIconName.ts, packages/components/src/components/Menu/Menu.stories.tsx, packages/components/src/components/Menu/Menu.tsx
Updates two components: 
- Allow menu items to be also ReactNode
- Change menu item color and background color when disabled
- Add trash-2 and pin icons
=> feat: update menu and icon components

.changeset/grumpy-numbers-serve.md, packages/components/src/components/FormInput/FormInput.stories.tsx, packages/components/src/components/FormInput/FormInput.tsx, packages/components/src/components/FormSelect/FormSelect.stories.tsx, packages/components/src/components/FormSelect/FormSelect.tsx, packages/components/src/components/FormTextArea/FormTextArea.stories.tsx, packages/components/src/components/FormTextArea/FormTextArea.tsx
While working with the ControlledFormSelect, I noticed that the FormSelect component has an extra div when there is no helpText message. This div has a marginTop that makes it difficult to align the component within a form with a different gap, for example. 
[It's recommended to avoid](https://css-tricks.com/component-spacing-design-system/) adding spaces in the components themselves because it makes it harder to reuse and encapsulate components. 
For this specific case, I would suggest we create a FormField component that has Label, children and HelpText/ErrorMessage, and then, aligned with Design Team, we set the spaces between them. We can also have a FormLayout, so we align a space and have it more consistently, without adding extra spaces, making it easy when we have design …
=> fix: remove extra space from FormSelect, FormInput, FormTextArea

.changeset/khaki-dots-flow.md, packages/eslint-config/package.json, yarn.lock
- These two were not update by dependabot and they have more recent versions
=> chore: update @typescript-eslint/parser and @typescript-eslint/eslint-plugin to 6.12.0

.changeset/rich-swans-ring.md, packages/components/src/components/ConfirmationModal/ConfirmationModal.test.tsx, packages/components/src/components/ConfirmationModal/ConfirmationModal.tsx
- Add onCancel optional callback to Confirmation Modal
=> chore: add optional callback to Confirmation Modal cancel button

.changeset/rich-pans-drop.md, packages/components/src/primitives/Box/Box.tsx
- Remove `borderTopRightRadius`, `borderTopLeftRadius`, `borderBottomRightRadius`, `borderBottomLeftRadius` because they were not working as expected
for example:
```javascript
export const Default = (): JSX.Element => (
<Box.div
backgroundColor="colorBackgroundInfo"
borderTopRightRadius="borderRadius20"
padding="space40"
>
I&apos;m some text in a box.
</Box.div>
);
```
results in
- This PR changes the type of `borderRadius` prop so it can accept borderRadius with different tokens like
so
```javascript
<Box.div
backgroundColor="colorBackgroundInfo"
borderRadius="borderRadius0 borderRadius0 borderRadius0 borderRadius50"
padding="space40"
>
I&apos;m some text in a box.
</Box.div>
```
- Change the props value and see it reflects on the storybook
=> fix: Remove border radius token that were not working, add correct type to multiple border radius

.changeset/heavy-ducks-hang.md, packages/components/src/components/FileUploader/FileUploader.tsx
- Add type `button` to CancelUploadButton to avoid triggering a submit when it's part of a form
=> fix: add type 'button' to cancel upload button

.changeset/dull-moose-fly.md, packages/components/src/components/ContentCard/ContentCard.tsx
This PR fixes the ContentCard component by removing the extra spaces when the image on the right does not fit the container. 
Before: 
After:
=> fix: [ContentCard] remove spaces when image does not fit container

.changeset/eighty-buses-speak.md, packages/components/src/components/Table/Table.tsx
After updating the Table component, we noticed that we were showing a scrollbar even if the table didn't need to scroll. This PR updates the `overflow` prop to `auto`.
=> fix: update overflow in table

.changeset/poor-penguins-vanish.md, packages/components/src/components/Table/Tr.tsx
Unset the `hover` attribute when the table row is not clickable.
=> fix: table row hover when it is not clickable

.changeset/real-sheep-double.md, packages/components/src/components/Table/Td.tsx
- Add `paddingBottom`, `paddingLeft`, `paddingRight` and `paddingTop` props to Td component making it optional `space0` or `space50`
=> chore: Add padding props to Td component

.changeset/rare-candles-mix.md, packages/components/src/components/Tabs/Tabs.stories.tsx, packages/components/src/components/Tabs/Tabs.tsx
For the new reporting graphs we will add tabs to the reporting page which breaks the AG Grid results as they use 100% height for the result set, which leads to no results at all being visible since the Tabs wrapper div has display block and therefore does not fill the whole view port height.
=> Add `flexed` option to `Tabs` component

.changeset/brave-oranges-lie.md, packages/components/src/components/Table/Table.stories.tsx, packages/components/src/components/Table/Tr.tsx
When we updated the Table component to unset the hover state when a row wasn't clickable, we broke the striped version, when isClickable and striped could not work at the same time. 
This PR adds a new property called `isHoverable` to the table row and makes it possible to be hoverable and striped at the same time. The `isClickable` prop now only changes the `cursor` to `pointer` when true. 
Besides that, I put it back the old background tokens because we need to first introduce the specific tokens like "bgHover" and then update them in places like tables.
All the examples can be seen [here](https://632b1baf1257171b6a84f370-nsoxbxopty.chromatic.com/?path=/docs/components-table--docs)
=> feat: add isHoverable prop to table row

.changeset/seven-trains-judge.md, packages/design-tokens/docs/borders.mdx, packages/design-tokens/docs/colors.mdx, packages/design-tokens/docs/components/TokensTable.tsx, packages/design-tokens/docs/components/constants.tsx, packages/design-tokens/docs/components/createPreview.tsx, packages/design-tokens/docs/font-sizes.mdx, packages/design-tokens/docs/font-weights.mdx, packages/design-tokens/docs/icon-sizes.mdx, packages/design-tokens/docs/spacing.mdx, packages/design-tokens/docs/types/TokenTuple.ts, packages/design-tokens/docs/utils/buildTokensTableRows.tsx, packages/design-tokens/docs/utils/getTokenComment.ts, packages/design-tokens/docs/utils/getTokenKey.ts, packages/design-tokens/docs/utils/getTokenName.tsx, packages/design-tokens/docs/utils/getTokenValue.ts
JSON files (for instance, color.tokens.json) already have multiple prefixes (color, bg, content, border, ...). This PR aims at enabling Storybook docs to show each token on the respective page.
Related with: https://linear.app/localyze/issue/TREX-1406/parse-pluto-tokens-so-docs-pages-show-all-prefixes-on-it
=> feat: Enable prefixes for multiple tokens on docs

.changeset/red-chefs-sin.md, packages/components/src/components/Drawer/Drawer.stories.tsx, packages/components/src/components/Drawer/Drawer.tsx
This PR adds a styled backdrop to the Drawer component. This component could use the `data-backdrop` attribute already present in `base.tsx` styles, but I decided not to change that right now to avoid impacting other components like Modal. 
Besides that, it fixes an issue with the initialFocus that was focusing the `X` button when the Drawer was opened.
https://github.com/Localitos/pluto/assets/5320963/350032b3-ff20-401e-82ae-582636f3efca
=> feat: add backdrop to drawer component

.changeset/rotten-ravens-nail.md, packages/components/src/components/Drawer/Drawer.test.tsx, packages/components/src/components/Drawer/Drawer.tsx
Adds transition when opening and closing Drawer component. 
https://github.com/Localitos/pluto/assets/5320963/01cc8ca1-7a02-4251-947e-ba50131fc09a
=> feat: add transition to drawer component

.changeset/happy-fans-itch.md, packages/components/src/components/Drawer/Drawer.stories.tsx, packages/components/src/components/Drawer/Drawer.tsx, packages/components/src/components/Drawer/DrawerBody.tsx, packages/components/src/components/Drawer/DrawerHeader.tsx, yarn.lock
Goal of the PR is to allow the Drawer component to receive padding as a Prop, therefore increasing its flexibility and allowing to meet the design goals stated here, where padding is 24px (space70).
=> [NO ISSUE] feat: allow Drawer to receive padding as prop

.changeset/tough-fans-tap.md, packages/components/src/components/UtilityCard/UtilityCard.stories.tsx, packages/components/src/components/UtilityCard/UtilityCard.test.tsx, packages/components/src/components/UtilityCard/UtilityCard.tsx, packages/components/src/index.ts
Allow UtilityCard to be used outside of Pluto. As of now, due to a missing export, it's an unrecognized import.
=> [NO ISSUE] fix: export UtilityCard to be used externally

.changeset/wicked-actors-ring.md, packages/components/src/components/Drawer/Drawer.test.tsx
- Change the place where the Drawer test has a click in order to fix flakiness
=> fix: avoid click on button to close

.changeset/small-hounds-destroy.md, packages/components/src/components/Pagination/Pagination.stories.tsx, packages/components/src/components/Pagination/PaginationButton.tsx
Fix the background of `PaginationButton`s that are not the current page. [According to Hanna](https://localyzeteam.slack.com/archives/C03DUMP3XD4/p1713269851623759?thread_ts=1713269362.203909&cid=C03DUMP3XD4) they should be transparent.
=> fix(components): Add transparent background for PaginationButton

.changeset/four-needles-argue.md, packages/components/src/components/Drawer/Drawer.test.tsx
- Add an element wrapping Drawer to remove transition on tests
=> fix: remove drawer animation on tests

.changeset/lemon-ties-chew.md, packages/components/src/components/Heading/Heading.tsx
- Add `colorTextStrongest` as option to Heading
=> chore: add colorTextStrongest as an option to Heading color

.changeset/modern-queens-sneeze.md, packages/components/src/components/ContentCard/ContentCard.stories.tsx, packages/components/src/components/ContentCard/ContentCard.tsx
- Add `isRounded` property to Content Card making it possible to remove border radius
=> feat(components): add isRounded property to ContentCard

.changeset/neat-wasps-yell.md, packages/components/src/components/Menu/Menu.tsx
- Add 100% width to the button on menu avoiding to be overwritten by previous button style
background added for pure debugging
before:
after:
=> fix(components): add button with 100% width correctly to menu

.changeset/olive-moons-smoke.md, packages/components/src/components/ContentCard/ContentCard.stories.tsx, packages/components/src/components/ContentCard/ContentCard.tsx
- Add a max-width prop to make it configurable
- Fix button width when image is on top
- Remove unused isRounded property
before:
after:
=> chore: make ContentCard maxWidth changeable, fix button width, remove unused prop

.changeset/neat-moose-brake.md, packages/components/src/components/Heading/Heading.tsx
- Update Heading to have m0 and m6 as possible marginBottom options
=> chore(components): add m0 and m6 margin tokens as options to heading

.changeset/perfect-bananas-play.md, packages/components/src/components/Paragraph/Paragraph.tsx
- Add m0 and m6 tokens as possible margins to Paragraph component
=> chore(components): allow Paragraph to use m0 and m6 as margin

.changeset/happy-moons-speak.md, packages/components/src/components/Label/Label.tsx, packages/components/src/components/List/OrderedList.tsx, packages/components/src/components/List/UnorderedList.tsx, packages/components/src/components/Paragraph/Paragraph.tsx, packages/components/src/components/Table/Td.tsx
- Apply the same interface fix to Label, OrderedList, UnorderedList, Paragraph, Td in order to allow things as `id`
=> fix(components): remove token limitations from some components

.changeset/ten-dryers-happen.md, package.json, packages/components/package.json, packages/design-tokens/package.json, packages/theme/package.json, yarn.lock
Update dependencies @hookform/resolvers, @tanstack/react-table, @babel/preset-env, cspell, husky, prettier, ts-jest, lucide-react, tsup
=> chore: bump dependencies

.changeset/happy-wombats-breathe.md, packages/eslint-config/package.json, yarn.lock
- It reverts last update since this new plugin needs eslint 9
=> fix(eslint): revert update parser since it needs eslint 9

.changeset/plenty-rats-love.md, packages/design-tokens/config.js, packages/design-tokens/src/tokens/space.tokens.json
- Add space prefix tokens as deprecated
- Change config logic to add @deprecated comment when the token is marked as such
=> chore(design-tokens): add prefix space tokens as deprecated

.changeset/odd-planets-visit.md, packages/components/src/components/Menu/Menu.tsx
The outline color of the menu is inconsistent with the rest of the border colors we use and e.g. also inconsistent with the current user menu we have in the classic app.
When replacing the old headlessUI menu with the Pluto menu the outline makes the borders look different than in all the other places.
=> fix(components): Update menu outline color to gray

.changeset/long-carpets-work.md, packages/components/src/components/Menu/Menu.stories.tsx, packages/components/src/components/Menu/Menu.tsx
- Allow BoxProps to be passed as properties to Menu component
- Add property to change menu z index when opened
example:
```jsx
<Box.div minHeight="100px">
<Menu items={items} menuButton={menuButton} menuZIndex="10" />
<Input type="text" />
</Box.div>
```
=> chore(components): allow box props to be added to Menu

.changeset/swift-apes-repeat.md, packages/components/src/components/Menu/Menu.tsx
- Add overflow hidden to menu so the square corners of the items are not shown outside of the container
BEFORE
AFTER
=> fix(components: Remove menu white corners by adding overflow hidden

.changeset/young-trains-matter.md, packages/components/src/components/Heading/Heading.tsx
We realized the need to update all places where the Heading component is used to apply `contentPrimary` as the color. To simplify this, we'll set `contentPrimary` as the default color to avoid making changes in multiple places.
This was agreed with Hanna, but also let me know what you think about it.
=> feat: update the Heading default color

.changeset/weak-moons-call.md, packages/design-tokens/docs/borders.mdx, packages/design-tokens/docs/colors.mdx, packages/design-tokens/docs/components/TokensTable.tsx, packages/design-tokens/docs/components/constants.tsx, packages/design-tokens/docs/components/createPreview.tsx, packages/design-tokens/docs/font-sizes.mdx, packages/design-tokens/docs/font-weights.mdx, packages/design-tokens/docs/icon-sizes.mdx, packages/design-tokens/docs/spacing.mdx, packages/design-tokens/docs/utils/getTokenNameFromTuple.ts
- Add a name property to TokensTable
- Add a null check to TokensTable to avoid breaking by accessing an undefined value
- Change TOKENS_TABLE to have one more level (or prefix) to each object. So a titleDisplay that comes from font-size would not collide with titleDisplay that comes from font-weight
- Call camelcase on tokens names avoiding things as `colorBackgrounddecorative-strong` correcting it to `colorBackgroundDecorativeStrong`
=> fix(docs): change TOKEN_COLUMNS to avoid conflicting tokens with the same name

.changeset/khaki-snakes-cough.md, packages/design-tokens/docs/borders.mdx, packages/design-tokens/docs/colors.mdx, packages/design-tokens/docs/font-sizes.mdx, packages/design-tokens/docs/font-weights.mdx, packages/design-tokens/docs/icon-sizes.mdx, packages/design-tokens/docs/spacing.mdx
- Add the correct prop on Tokens table on the documentation pages
=> fix(docs): add right prop category to table

.changeset/four-games-nail.md, packages/components/src/components/Select/Select.stories.tsx, packages/components/src/components/Select/Select.tsx
When exposing the `sameWidth` property, we forgot to set its default value to true, as all usage of Select component was already configured to use it that way.
=> fix: set sameWidth from Select as default true

.changeset/quiet-rockets-tap.md, packages/components/src/components/Drawer/DrawerHeading.tsx, packages/components/src/components/Modal/ModalHeading.tsx
After updating the `Heading` default color ( in https://github.com/Localitos/pluto/pull/1731), we realized that there are still headings using the prior color. With this change we should have address all headings and have the same color.
DrawerHeading
ModalHeading
=> feat: Update default color ModalHeading DrawerHeading

.changeset/cold-news-glow.md, packages/components/src/components/ContentCard/ContentCard.stories.tsx, packages/components/src/components/ContentCard/ContentCard.tsx
This PR:
* has a breaking change because it changes the `iconUrl` prop to `topLeftElement` since it will accept ReactNode instead of only string. This allows us to use different image components, like Image from nextjs or other type of elements
* adds a new `topRightElement` prop so we allow adding an element in the top right corner of the card
* adds a new `lowOpacity` prop to set the opacity of the card content without including the `topRightElement`
* fixes some style inconsistencies (heading, card content) between the component in Figma and the one from Pluto
* adds `h` and `w` properties to allow setting custom width and height for the card
Disclaimer: we don't have any usage of the `iconUrl`, but I decided to make it a breaking change because of semantics.
=> feat: update ContentCard component

.changeset/ninety-bikes-reply.md, packages/components/src/components/ContentCard/ContentCard.stories.tsx, packages/components/src/components/ContentCard/ContentCard.tsx
* Updates the ContentCard's content height to fill all the available space
* Moved the button to the bottom of the content area for better and consistent placement
* Changed the `InList` story to `InListWithImageOnTop` so it's better to see how the cards look like inside a grid
Explanation:
While updating the latest version of Pluto in the classic app, I saw that the cards in the Integrations list were not aligned correctly because the text in one card was smaller than the others. Even after fixing the content height to use all the space, the cards still didn’t align correctly when there was a button. To fix this, I decided to move the button to the bottom.
Bug:
Fix:
=> fix: update content height to fill available space

.changeset/weak-impalas-travel.md, packages/components/src/components/Tabs/Tab.tsx, packages/components/src/components/Tabs/TabList.tsx, packages/components/src/components/Tabs/Tabs.stories.tsx, packages/components/src/components/Tabs/Tabs.tsx, packages/components/src/components/Tabs/TabsContext.tsx, packages/components/src/components/Tabs/index.ts, packages/components/src/components/Tabs/types.ts
Breaking changes:
* Removed the `flexed` prop from the Tabs component, as it is now the default behavior.
* Removed the `variant` prop from the Tabs component since it wasn't used in the component.
Minor changes:
- The `TabsList` component now accepts a `fullWidth` prop allowing the tabs list to expand to the full width.
- Fixed a bug with the focus indicator, switching from focus to focus-visible for better accessibility.
- Fixed styles of the Tabs to be more consistent with Figma
The bug with the focus:
With the fix:
=> fix: improve usability of Tabs component

.changeset/new-rivers-hide.md, packages/components/src/components/UtilityCard/UtilityCard.stories.tsx, packages/components/src/components/UtilityCard/UtilityCard.test.tsx, packages/components/src/components/UtilityCard/UtilityCard.tsx
Now we save the category specific emoji in the DB so we don't need to load any emoji-images anymore.
- update UtilityCard to use emoji/string instead of image
This should only be merged with the relevant change in the Localitos/Backend (WIP)
=> Update utility card to use emoji instead of image

packages/components/src/components/List/OrderedList.tsx, packages/components/src/components/List/UnorderedList.tsx
- Change styled default import by named on components fixing a warning https://github.com/Localitos/pluto/pull/1767/files#file-packages-components-src-components-list-orderedlist-tsx-L2
=> fix(components): import named styled instead of default fixing warning

.changeset/late-plants-clap.md, packages/components/src/components/ContentCard/ContentCard.stories.tsx, packages/components/src/components/ContentCard/ContentCard.test.tsx, packages/components/src/components/ContentCard/ContentCard.tsx
While working on adding the Link from react router to the ContentCard component in the Partners list page, I noticed that it was creating the following issue:
This is happening because when using the `InteractiveElementType.Card`, the component automatically wraps the card in an <a> tag.
To avoid this issue and allow the card to be interactive without always being a link, I removed this behavior, letting the user add a link tag if needed.
=> feat: remove default link tag from interactive content card

.changeset/fast-mice-applaud.md, packages/components/src/components/Menu/Menu.stories.tsx, packages/components/src/components/Menu/Menu.tsx, packages/components/src/components/Menu/index.ts
While working on the Partner Preferences page and adding the menu `Set preferences` there, I noticed that we had some issues with the Menu component and decided to make some improvements. Changelog:
* Breaking change: Removed the unnecessary div wrapper from the Menu component; props are now passed directly to the Menu.
* Improved focus behavior for menu items by adding a background color to the focused item
* Added a new customStore prop to enable custom store settings and support different behaviors, such as placement
* Set a default gutter value of 3 for the Menu component to align with the Figma design
* Introduced a menuButtonProps prop to enable passing props to the default menu button
This component was limited to its own store. With this change, we can now customize things like …
=> feat: make improvements to Menu component

.changeset/early-badgers-trade.md, packages/components/src/components/Combobox/Combobox.stories.tsx, packages/components/src/components/Combobox/Combobox.test.tsx, packages/components/src/components/Combobox/Combobox.tsx, packages/components/src/components/Combobox/ComboboxInput/ComboboxInput.test.tsx, packages/components/src/components/Combobox/ComboboxInput/ComboboxInput.tsx, packages/components/src/components/Combobox/ComboboxItem/ComboboxItem.test.tsx, packages/components/src/components/Combobox/ComboboxItem/ComboboxItem.tsx, packages/components/src/components/Combobox/ComboboxPopover/ComboboxPopover.test.tsx, packages/components/src/components/Combobox/ComboboxPopover/ComboboxPopover.tsx, packages/components/src/components/Combobox/ComboboxProvider/ComboboxProvider.tsx, packages/components/src/components/Combobox/index.ts, packages/components/src/index.ts
Introduces new `Combobox` component:
- Combines a text input and a popover to allow users to filter from long lists of options
- Can be used as a standalone component or composed with other components such as `ComboboxInput`, `ComboboxPopover`, `ComboboxItem`, and `ComboboxProvider`
- Supports generic type for the options list
- Provides a prop `filterItem` prop to be used as the filter function when receiving a function.
=> add new Combobox component

.changeset/green-keys-marry.md, .changeset/proud-apes-confess.md, packages/components/src/components/UtilityCard/UtilityCard.stories.tsx, packages/components/src/components/UtilityCard/UtilityCard.test.tsx, packages/components/src/components/UtilityCard/UtilityCard.tsx
Breaking Change:
- Removed the `interactiveElementType` prop in order to add two new states properties `hoverable` and `clickable`
- Renamed `categoryTag` to `subTitle` to make it more generic
- `onClick` prop is only required when using `clickable` as true
Minor:
- Added `hoverable` and `clickable` to have more control of state of the card
- Added `emojiWrapperSize` prop with options `small` and `large` so it's adaptable to different use cases
- Added `indicator` to add a helper element to the top right of the card
=> feat: use proper states and make UtilityCard more generic

.github/workflows/on_pull_request.yml
- Our actions are breaking because this action is outdated. This PR updates to V3
=> chore: update cache action to version 3
