Localitos/pluto

CONTRIBUTING.md

Just fixing the contributing doc, and how to start storybook.

fix: correct storybook start command

---

.github/workflows/on_release_publish.yml

This fixes the release version package PR commit message error.

fix: add commit message to release

---

.github/workflows/auto_assign_owner.yml
cspell.json

Adds an action to automatically assign a PR author as an assignee.

feat: add github action to assign owner to PR

---

README.md
cspell.json

Just a minor change to the readme about loading fonts. Also updated the install packages to the correct name, and removed icons since that doesn't exist yet.

chore: add font section to readme

---

.github/workflows/visual_regression_tests.yml
.gitignore
cspell.json
package.json
packages/components/src/primitives/Box/BaseBox.tsx

This PR setups Chromatic to Pluto:

feat: setup chromatic to Pluto

---

package.json
yarn.lock

Updating TurboRepo and removing `run` from the `turbo` scripts. [More info here](https://turborepo.org/blog/turbo-1-5-0#drop-the-run).

chore: update turborepo, change scripts

---

README.md

Removes Netlify from the build step. Mostly config changes on the Netlify side, and a small change in the readme.

chore: remove netlify from build

---

.github/workflows/visual_regression_tests.yml

I tried with `branches-ignore` and it didn't work. Now I'm trying again with the github.triggering_actor check. 🤷🏻‍♀️

chore: avoid running vrt on dependabot prs

---

.github/workflows/on_pull_request.yml
.gitignore
dangerfile.ts
package.json
yarn.lock

Adding dangerjs for PR checks
Initial rule checks presence of changelog file

chore: add dangerjs

---

.github/workflows/visual_regression_tests.yml

Fix dependabot author's name on vrt action:

fix: dependabot name on vrt action

---

.github/workflows/visual_regression_tests.yml

fix: dependabot

---

.github/workflows/visual_regression_tests.yml

fix: update if conditional on vrt action

---

.github/workflows/on_pull_request.yml

Avoid running danger for dependabot and draft PRs

fix: avoid running danger for dependabot and draft PRs

---

.changeset/plenty-tables-appear.md
packages/theme/src/index.ts

Forgot to export `createGlobalStyle` from xStyled.

chore(theme): export createGlobalStyle from xStyled

---

README.md

Adding information about the ThemeProvider to the readme.

chore: update readme with theme provider info

---

.changeset/giant-stingrays-trade.md
package.json
packages/components/src/components/Button/Button.tsx
packages/components/src/components/Table/TBody.tsx
packages/components/src/components/Table/THead.tsx
packages/components/src/components/Table/Table.stories.tsx
packages/components/src/components/Table/Table.test.tsx
packages/components/src/components/Table/Table.tsx
packages/components/src/components/Table/Td.tsx
packages/components/src/components/Table/Th.tsx
packages/components/src/components/Table/Tr.tsx
packages/components/src/components/Table/index.ts
packages/components/src/index.ts
yarn.lock

Sets up the un-styled composable Table components and parts. Includes stories and tests.

feat(components): add table component

---

.changeset/fluffy-cougars-thank.md
.changeset/wise-steaks-burn.md
packages/components/src/components/Anchor/Anchor.stories.tsx
packages/components/src/components/Anchor/Anchor.test.tsx
packages/components/src/components/Anchor/Anchor.tsx
packages/components/src/components/Anchor/index.ts
packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
packages/theme/src/theme/default.ts

- Add anchor component
- Add visited token for anchors

feat(components): add anchor

---

.changeset/silent-crabs-turn.md
packages/components/package.json
packages/components/src/components/RichText/RichText.stories.tsx
packages/components/src/components/RichText/RichText.test.tsx
packages/components/src/components/RichText/RichText.tsx
packages/components/src/components/RichText/index.ts
packages/components/src/index.ts
yarn.lock

Adds the RichText component to be used in the RichText editor that we will add soon. This component was created by @richbachman in some of our internal repo at Localyze and now we are moving to our design system.

feat(components): add RichText component

---

.changeset/good-spiders-search.md
packages/components/src/index.ts

fix(components): make anchor component public

---

.changeset/healthy-moles-study.md
packages/components/src/components/Callout/Callout.tsx

Remove the padding from Callout without background.

fix(components): update callout padding

---

.changeset/swift-moose-deny.md
.changeset/tame-suns-unite.md
packages/components/src/components/Badge/Badge.stories.tsx
packages/components/src/components/Badge/Badge.test.tsx
packages/components/src/components/Badge/Badge.tsx
packages/components/src/components/Badge/index.ts
packages/components/src/index.ts
packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
packages/theme/src/theme/default.ts

This is a PR to add the Badge component

feat(components): add badge

---

.changeset/hip-queens-double.md
packages/components/src/components/Button/Button.tsx

fix(components): adjust small button sizes

---

.changeset/heavy-clouds-remain.md
packages/components/src/components/Input/Input.tsx
packages/components/src/components/InputBox/InputBox.tsx

Add type `datetime-local` to input type

feat(components): add type datetime-local to input type

---

.changeset/hip-parents-obey.md
packages/components/src/components/Button/Button.stories.tsx
packages/components/src/components/Button/Button.tsx
packages/components/src/components/Checkbox/Checkbox.stories.tsx

feat(components): add button text variant

---

.changeset/sharp-mice-marry.md
packages/components/src/components/Button/Button.stories.tsx
packages/components/src/components/Button/Button.tsx

This PR adds the secondary button variant. 

feat(components): add secondary button variant

---

.changeset/few-carrots-heal.md
packages/components/package.json
packages/components/src/components/ProgressBar/ProgressBar.stories.tsx
packages/components/src/components/ProgressBar/ProgressBar.test.tsx
packages/components/src/components/ProgressBar/ProgressBar.tsx
packages/components/src/components/ProgressBar/index.ts
packages/components/src/index.ts
yarn.lock

This PR adds the first version of ProgressBar component.

feat(components): add progressbar component

---

.changeset/clever-tigers-collect.md
.changeset/nasty-fishes-relate.md
.changeset/shy-trains-greet.md
packages/components/src/components/Badge/Badge.stories.tsx
packages/components/src/components/Badge/Badge.tsx
packages/design-tokens/src/tokens/color.tokens.json
packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
packages/theme/src/theme/default.ts

Added a purple Badge variant and necessary tokens to support it.

chore(components): added purple badge variant

---

.changeset/tender-weeks-sell.md
.jest/jest-setup.ts
packages/components/src/components/Button/Button.stories.tsx
packages/components/src/components/Button/Button.test.tsx
packages/components/src/components/Button/Button.tsx

- Renames the `text` variant to `ghost`
- Enables `iconOnly` version
- Refactores stories to have all variants statuses 
- Fixes active and focus states

feat(components): add ghost button variant

---

.changeset/purple-garlics-check.md
packages/components/src/components/List/OrderedList.tsx
packages/components/src/components/List/UnorderedList.tsx
packages/components/src/components/RichText/RichText.stories.tsx
packages/components/src/components/RichText/RichText.tsx

Renders lists and bold on RichText component.

feat(components): add lists and bold to RichText component

---

.changeset/shy-peaches-grow.md
packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
packages/theme/src/theme/default.ts

Adds new colorBackgroundBodyStrong bg color to theme

feat(theme): add new colorBackgroundBodyStrong bg color to theme

---

.changeset/cuddly-kangaroos-pull.md
packages/components/src/components/FileUploader/FileUploader.stories.tsx
packages/components/src/components/FileUploader/FileUploader.tsx

Adjust the button height when the file uploader label has more than one line.

fix(components): adjust button height on file uploader

---

.changeset/eighty-rings-serve.md
packages/components/src/components/FileUploader/FileUploaderDescription.tsx

This PR adds a textColor to the FileUploaderDescription component.

feat(components): update file uploader description text color

---

.changeset/fuzzy-pans-behave.md
packages/components/src/index.ts

Fixes the component export to include Dropzone.

fix(components): fix dropzone export

---

README.md

Just added a link to to the contributing doc in the readme.

chore: add contributing link to readme

---

.github/pr-labeler-config.yml
.kodiak.toml

Sets up the [Kodiak](https://kodiakhq.com/) config file for auto merging PRs. This still requires us to add a label to auto merge the PRs, just so we have a little more control while we test this feature.

chore: setup kodiak config

---

.changeset/wicked-seas-switch.md
packages/components/src/components/Dropzone/Dropzone.tsx
packages/components/src/components/Dropzone/getFileRestrictionText.ts

The error message in the dropzone was not using the updated method to include kb so I added that.

fix(components): adjusted file size error msg in dropzone for kb

---

.changeset/yellow-houses-kick.md
packages/components/src/components/Icon/Icon.tsx

Added `vericalAlign` and `display` to the icon svg so we can get away with not using `Preflight` in the client app.

fix(components): add icon alignment and display

---

.changeset/thin-colts-appear.md
packages/components/package.json
packages/components/src/components/Toast/Toast.stories.tsx
packages/components/src/components/Toast/Toast.test.tsx
packages/components/src/components/Toast/Toast.tsx
packages/components/src/components/Toast/ToastViewport.tsx
packages/components/src/components/Toast/index.ts
packages/components/src/components/Toast/types.ts
packages/components/src/index.ts
yarn.lock

This adds the Toast with success and error variants. Stories and test are included.

feat(components): add Toast component

---

.changeset/brave-cats-switch.md
packages/components/src/components/Dropzone/Dropzone.stories.tsx
packages/components/src/components/Dropzone/Dropzone.tsx

The dropzone's isloading state was not taking into account if an error occurred so we added that here.

feat: [no-issue] fixed dropzone isloading state to include error

---

.changeset/itchy-seals-explode.md
packages/components/src/components/Select/Select.tsx

Fixes a style error I introduced for the initial selected item color.

fix(components): correct the starts with error for initial

---

.changeset/sixty-teachers-bake.md
packages/components/src/components/Dropzone/Dropzone.tsx

The errors were not being cleared when the file dialog was being opened, so this is adding function (onFileDialogOpen) and clearing the errors when it is opened.

fix(components): cleared errors onFileDialogOpen

---

.changeset/grumpy-birds-listen.md
packages/components/src/components/Button/Button.stories.tsx
packages/components/src/components/Button/Button.tsx

Added the desctructive variant to Button.

feat(components): added destructive button variant

---

.changeset/blue-kings-fix.md
packages/components/src/components/Select/index.ts

Export `SelectItemProps` for use in client applications.

chore(components): export SelectItemProps

---

.changeset/beige-cycles-buy.md
packages/components/src/components/Input/Input.stories.tsx
packages/components/src/components/StepIndicator/StepIndicator.stories.tsx
packages/components/src/components/StepIndicator/StepIndicator.test.tsx
packages/components/src/components/StepIndicator/StepIndicator.tsx
packages/components/src/components/StepIndicator/StepIndicatorSegment.tsx
packages/components/src/components/StepIndicator/index.ts
packages/components/src/index.ts

Added StepIndicator components, stories, and tests.

feat(components): added StepIndicator component

---

.changeset/silver-beans-switch.md
packages/components/src/components/Dropzone/Dropzone.tsx

As per a great suggestion by @FranziGrieser we are updating the cursor for the dropzone to pointer here.

fix(components): added cursor pointer to dropzone

---

.changeset/chatty-roses-change.md
packages/components/src/components/Heading/Heading.tsx

Sets the text-transform style for Heading so any other framework styles don't overwrite it.

fix(components): fix heading text-transform style

---

.changeset/lemon-zebras-admire.md
packages/components/src/components/FormInput/FormInput.stories.tsx
packages/components/src/components/FormInput/FormInput.test.tsx
packages/components/src/components/FormInput/FormInput.tsx
packages/components/src/components/FormInput/index.ts
packages/components/src/index.ts

Added FormInput component, stories, and tests.

feat(components): added FormInput component

---

.changeset/shiny-bobcats-compete.md
packages/components/src/components/FormInput/FormInput.tsx
packages/components/src/components/FormSelect/FormSelect.stories.tsx
packages/components/src/components/FormSelect/FormSelect.test.tsx
packages/components/src/components/FormSelect/FormSelect.tsx
packages/components/src/components/FormSelect/index.ts
packages/components/src/components/FormTextArea/FormTextArea.stories.tsx
packages/components/src/components/FormTextArea/FormTextArea.test.tsx
packages/components/src/components/FormTextArea/FormTextArea.tsx
packages/components/src/components/FormTextArea/index.ts
packages/components/src/index.ts

Added the FormSelect and FormTextArea components, stories, and tests.

feat(components): add FormSelect and FormTextarea

---

.changeset/many-papayas-jog.md
packages/components/src/components/StepIndicator/StepIndicator.stories.tsx
packages/components/src/components/StepIndicator/StepIndicator.tsx
packages/components/src/components/StepIndicator/StepIndicatorSegment.tsx
packages/components/src/components/Table/Table.stories.tsx
packages/components/src/components/Table/Table.tsx
packages/components/src/components/Table/TableContext.tsx
packages/components/src/components/Table/Td.tsx
packages/components/src/components/Table/Th.tsx

- [Table] - added `bordered` prop to add vertical borders to the tables THs and TDs.
- [Table] - added `textAlign` prop to TH and TD.
- [StepIndicator] - fixed the color of for completed step.

feat(components): added bordered and textAlign to table

---

.changeset/eleven-dodos-guess.md
packages/components/src/components/Table/Table.stories.tsx
packages/components/src/components/Table/Tr.tsx

Added to Tr in Table:
- hover: colorBackgroundWeak
- isClickable
- pointer: cursor if isClickable
- WithClickableRows story
https://user-images.githubusercontent.com/52461415/214567007-b68edb69-7461-4bbd-95cd-085040a0af4e.mov

feat(components): added hover colorBackgroundWeak and isClickable to Tr in Table

---

.changeset/eighty-laws-join.md
package.json
packages/components/src/components/FormInput/ControlledFormInput.tsx
packages/components/src/components/FormInput/FormInput.stories.tsx
packages/components/src/components/FormInput/FormInput.test.tsx
packages/components/src/components/FormInput/FormInput.tsx
packages/components/src/components/FormInput/index.ts
packages/components/src/components/Input/Input.tsx
yarn.lock

Added a ControlledFormInput component for easier use with React Hook Form.

feat(components): add ControlledFormInput for react hook form

---

.github/CODEOWNERS

* Remove Rich as code owner
* Add Dani since she is interested in being a code owner again of Pluto

chore: update list of code owners

---

.changeset/great-weeks-sort.md
packages/components/src/index.ts

It looks like this was developed but not exported for use. It looks ready to me, anyone know if there was a reason? @blumaa it looks like you worked on this, any idea?

feat: export Radio component

---

.changeset/eighty-sheep-appear.md
.changeset/slimy-crabs-attend.md
packages/components/src/components/Checkbox/index.ts

Whoops, forgot to export the new ControlledCheckbox component.

Export controlled checkbox

---

.changeset/smooth-mugs-relate.md
packages/components/src/components/FileUploader/FileUploader.stories.tsx
packages/components/src/components/FileUploader/FileUploader.tsx
packages/components/src/components/FileUploader/FileUploaderIcon.tsx
packages/components/src/components/FileUploader/FileUploaderTitle.tsx
packages/components/src/components/FileUploader/utils/getStatus.test.ts
packages/components/src/components/FileUploader/utils/getStatus.ts

Use `disabled` prop instead of creating a disabled status.

fix: [FileUploader] remove disabled status and use disabled prop

---

.changeset/sweet-cameras-attack.md
packages/components/src/components/Icon/Icon.stories.tsx
packages/design-tokens/src/tokens/size.tokens.json
packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap

- Adding more values to icon sizes 50, 60, 70

feature: Add icon size tokens

---

.changeset/tender-weeks-smoke.md
packages/components/package.json
yarn.lock

Run yarn build and check that the application still runs properly and you're able to see all components in Storybook.

chore(components): bump ariakit to 2.0.0-next.44

---

.changeset/popular-tables-warn.md
package.json
packages/components/package.json
packages/theme/package.json
yarn.lock

Update react-testing library to 14

fix(components): update react testing library to 14

---

jest.config.js

- Ignore stories files when instrumenting code coverage

chore: ignore stories files on code coverage

---

CONTRIBUTING.md
cspell.json

- I believe that there are more smooth ways to handle yalc but this is a good start

chore: adding instructions to yalc use

---

.github/workflows/on_pull_request.yml
.github/workflows/on_pull_request_package_size.yml
.github/workflows/on_release_publish.yml
.gitignore

Updating the github/workflows to nodejs 20.3.1

[no-issue] feat: update nodejs to 20.3.1

---

.changeset/funny-points-tan.md
packages/components/src/components/Menu/Menu.stories.tsx
packages/components/src/components/Menu/Menu.test.tsx
packages/components/src/components/Menu/Menu.tsx
packages/components/src/components/Menu/index.ts

Add a menu component (dropdown).
---
---
https://github.com/Localitos/pluto/assets/6059188/497b3950-3bb4-4dbb-abf5-a7533b523e6a

feat: add menu component

---

.changeset/tall-clouds-attack.md
packages/components/src/index.ts

Export the menu component so we can use it in the classic app

fix(commponents): export menu component

---

packages/components/package.json
packages/components/src/components/Icon/LucideIcons.ts
yarn.lock

Lucid React was in 0.218.0 version and we need some of the icons present in the new version 0.288.0

chore: update lucid-react version

---

.changeset/small-carpets-kick.md
packages/components/src/components/FileUploader/FileUploader.stories.tsx
packages/components/src/components/FormInput/FormInput.stories.tsx
packages/components/src/components/FormTextArea/FormTextArea.stories.tsx

[components] fix: import uppy differently, add trigger to dependency arrays

---

.changeset/tricky-ligers-add.md
packages/components/package.json
packages/design-tokens/package.json
packages/eslint-config/.eslintrc.js
packages/eslint-config/package.json
packages/theme/package.json
yarn.lock

chore: update tslib, typescript eslint and typescript parser

---

CONTRIBUTING.md

Add some information about ariakit to CONTRIBUTING.md

Add some information about ariakit to CONTRIBUTING.md

---

.changeset/tender-cars-warn.md
packages/components/src/components/Icon/LucideIcons.ts
packages/components/src/components/Icon/types/LucideIconName.ts

feat: add pin-off icon

---

.changeset/chilly-geese-reflect.md
packages/components/src/components/Menu/Menu.stories.tsx
packages/components/src/components/Menu/Menu.tsx

Fixes issues with the Menu component and adds minW and maxW as shown in Figma styles. 
Before: 
After:

fix: issues with menu component

---

packages/components/src/components/Button/Button.test.tsx
packages/components/src/components/Checkbox/ControlledCheckbox/ControlledCheckbox.test.tsx
packages/components/src/components/Drawer/Drawer.test.tsx
packages/components/src/components/Dropzone/Dropzone.test.tsx
packages/components/src/components/FileUploader/FileUploader.test.tsx
packages/components/src/components/FileUploader/FileUploaderButton.test.tsx
packages/components/src/components/FormInput/FormInput.test.tsx
packages/components/src/components/FormSelect/FormSelect.test.tsx
packages/components/src/components/FormTextArea/FormTextArea.test.tsx
packages/components/src/components/Menu/Menu.test.tsx
packages/components/src/components/Modal/Modal.test.tsx
packages/components/src/components/Pagination/Pagination.test.tsx
packages/components/src/components/Radio/ControlledRadioGroup/ControlledRadioGroup.test.tsx
packages/components/src/components/Radio/Radio.test.tsx
packages/components/src/components/Switch/Switch.test.tsx
packages/components/src/components/Table/Table.test.tsx
packages/components/src/components/Tabs/Tabs.test.tsx
packages/components/src/components/Toast/Toast.test.tsx
packages/components/src/components/Tooltip/Tooltip.test.tsx
packages/components/src/primitives/Box/Box.test.tsx

This fixes the ESlint warning.

Remove default import of userEvent

---

.changeset/tricky-mangos-sit.md
package.json
yarn.lock

chore: Update storybook addon links

---

.changeset/thick-bulldogs-reflect.md
package.json
yarn.lock

chore: update assert

---

.changeset/thin-jars-smash.md
.husky/commit-msg
packages/components/README.md

- Avoid running commitlint until it's fixed

fix: avoid running commitlint until it is fixed

---

.changeset/happy-houses-repeat.md
packages/components/src/components/Avatar/getAvatarColor.ts
packages/eslint-config/package.json
yarn.lock

chore: update @typescript-eslint plugin and parser to 6.13.1

---

.changeset/tame-rings-compare.md
packages/components/src/components/Icon/LucideIcons.ts
packages/components/src/components/Icon/types/LucideIconName.ts

fix(components): add check-square lucid icon

---

.changeset/sharp-garlics-warn.md
packages/components/src/components/Icon/LucideIcons.ts
packages/components/src/components/Icon/types/LucideIconName.ts

- Add calendar icon from the Lucide

chore: Add Calendar icon from lucide package

---

.changeset/thick-flies-look.md
packages/design-tokens/src/tokens/font-family.tokens.json
packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap

- We couldn't completely remove Moderat font before because builds would break because tokens

chore: Replace Moderat font by Noto Sans

---

.changeset/sweet-insects-count.md
packages/components/README.md

chore: Bump packages

---

.changeset/hungry-jokes-confess.md
packages/components/README.md
packages/eslint-config/.eslintrc.js
packages/eslint-config/package.json
packages/tsconfig/package.json

chore: update dependencies

---

.changeset/six-pants-provide.md
packages/components/src/components/Table/Table.tsx

This PR will add a gray outline and a wrapper with a background color white to the Table component.

feat: add border and background color white to Table component

---

.changeset/eighty-cheetahs-smoke.md
packages/design-tokens/README.md
packages/eslint-config/package.json
packages/theme/package.json

chore: Bump dependencies

---

.changeset/itchy-cows-hunt.md
packages/components/src/components/Badge/Badge.stories.tsx
packages/components/src/components/Badge/Badge.tsx

Add red variant to Badge component

feat(components): add red variant for badge

---

.changeset/heavy-paws-perform.md
packages/components/src/components/ContentCard/ContentCard.tsx

Improve how image and content are split in the ContentCard

feat: improve how image and content are split

---

packages/components/package.json
packages/theme/package.json
yarn.lock

- Update @types/react from 18.2.65 to 18.2.67

chore: update @types/react from 18.2.65 to 18.2.67

---

.changeset/grumpy-countries-relax.md
packages/components/README.md
packages/design-tokens/README.md
packages/eslint-config/package.json
packages/theme/README.md

chromatic
react-hook-form
@tanstack/react-table
@testing-library/react
@types/react
@commitlint/cli
@babel/preset-env
turbo
eslint-config-turbo
eslint-plugin-react
@typescript-eslint/eslint-plugin
@typescript-eslint/parser

chore: Update internal packages

---

.changeset/silent-rocks-pay.md
packages/components/README.md
packages/design-tokens/README.md
packages/eslint-config/package.json
packages/theme/README.md

update: 
```
storybook
@testing-library/react
@uppy/core
tar
@babel/preset-env
jest-fail-on-console
eslint-plugin-unicorn
eslint-plugin-jsdoc
eslint-plugin-jest
@typescript-eslint/parser
@typescript-eslint/eslint-plugin
typescript
@types/react
```

chore: enforce package new version to update internal dependencies

---

.github/dependabot.yml

- Reduces dependabot PRs limit

chore: reduce dependabot limit

---

package.json
packages/components/src/components/FormSelect/FormSelect.stories.tsx
yarn.lock

chore: update packages from root package.json

---

.changeset/thin-cheetahs-develop.md
packages/components/README.md
packages/design-tokens/README.md
packages/eslint-config/package.json
packages/theme/README.md

react-hook-form
@radix-ui/react-radio-group
lucide-react
react-hook-form
@radix-ui/react-radio-group
lucide-react
react-hook-form
@testing-library/jest-dom
@testing-library/react
@types/jest
jest
@localyze-pluto/tsconfig
@testing-library/jest-dom
@testing-library/react
@types/jest
@types/react
@types/react-dom
jest
react
react-dom
styled-components
ts-jest

chore: bump pluto version to update internal dependencies

---

.changeset/great-flies-yawn.md
packages/design-tokens/src/tokens/color.tokens.json

- Add color tokens that were duplicated as variables

chore: Replace duplicated tokens

---

.changeset/shaggy-kangaroos-yawn.md
packages/components/src/components/Toast/Toast.tsx

- Make the close Icon to be rendered as a button

fix (components): change close button as a button instead of a div

---

.changeset/early-rivers-cough.md
packages/components/src/components/Icon/LucideIcons.ts
packages/components/src/components/Icon/types/LucideIconName.ts

Adds the "List" icon from Lucid.

feat: add new list icon

---

.changeset/ten-cameras-end.md
packages/components/package.json
packages/design-tokens/package.json
packages/eslint-config/package.json
packages/theme/package.json
yarn.lock

- Update typescript and eslint packages

chore: bump typescript and eslint packages

---

yarn.lock

- This is probably the result of applying deduplicate and not running yarn on the root folder

fix: add correct yarn.lock

---

.changeset/sharp-yaks-provide.md
packages/components/src/components/Drawer/DrawerHeader.tsx
packages/components/src/components/Label/Label.tsx
packages/components/src/components/List/OrderedList.tsx
packages/components/src/components/List/UnorderedList.tsx
packages/components/src/components/Modal/ModalBody.tsx
packages/components/src/components/Table/Td.tsx

- Allow new tokens (same result) to DrawerHeader, Label, OrderedList, ModalBody, UnorderedList

chore(components): add new tokens as possibilities to space props

---

.changeset/four-olives-sort.md
packages/components/src/components/Drawer/DrawerHeader.tsx
packages/components/src/components/Heading/Heading.tsx
packages/components/src/components/Label/Label.tsx
packages/components/src/components/List/OrderedList.tsx
packages/components/src/components/List/UnorderedList.tsx
packages/components/src/components/Modal/ModalBody.tsx
packages/components/src/components/Paragraph/Paragraph.stories.tsx
packages/components/src/components/Paragraph/Paragraph.tsx
packages/components/src/components/Table/Td.tsx

- Remove token limitations from components below to make them easily changeable 
```
DrawerHeader
Heading
Label
OrderedList
UnorderedList
ModalBody
Paragraph
Td
```

chore(components):  remove tokens limitations

---

.changeset/breezy-cooks-bow.md
packages/components/src/components/Anchor/Anchor.tsx
packages/components/src/components/Avatar/Avatar.tsx
packages/components/src/components/Button/Button.tsx
packages/components/src/components/HelpText/HelpText.tsx
packages/components/src/components/Icon/Icon.tsx
packages/components/src/components/Input/Input.tsx

Remove token limitations from components:
```
Anchor
Avatar
Button
Checkbox
HelpText
Icon
Input
```

chore(components): Remove token limitations from some components

---

.changeset/smart-years-reflect.md
packages/components/package.json
packages/design-tokens/package.json
packages/eslint-config/package.json
packages/theme/package.json
yarn.lock

chore: bump eslint plugins and typescript

---

.changeset/weak-ghosts-accept.md
packages/eslint-config/package.json
yarn.lock

- Update packages to use both major updates

chore: Update packages: @typescript-eslint/eslint-plugin and @typescript-eslint/parser

---

.changeset/pretty-beers-wave.md
packages/components/src/components/Icon/LucideIcons.ts
packages/components/src/components/Icon/types/LucideIconName.ts

feat: add globe lucid icon

---

.changeset/four-adults-poke.md
package.json
packages/design-tokens/package.json
packages/theme/package.json
yarn.lock

- Update @types/jest, jest-fail-on-console, ts-jest

chore: Update jest related packages

---

.changeset/metal-roses-brake.md
packages/components/package.json
packages/components/src/components/ConfirmationModal/ConfirmationModal.test.tsx
packages/components/src/components/Modal/Modal.test.tsx
packages/components/src/components/Tabs/Tabs.test.tsx
packages/components/src/components/Tooltip/Tooltip.test.tsx
yarn.lock

chore: update ariakit-react to v0.4.15

---

.changeset/tall-cows-rescue.md
package.json
packages/components/package.json
packages/design-tokens/package.json
packages/theme/package.json
yarn.lock

bump typescript, ts-jest and tsup

chore: bump typescript, ts-jest and tsup
